server:
  port: 19097

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://localhost:8090/eureka/

google:
  driver:
    path: D:\chromedriver\chromedriver_win32\chromedriver.exe

spring:
  application:
    name: gn-reptile

  rabbitmq:
    host: 192.168.3.129 #ip
    port: 5672 #端口
    username: guest # 用户名
    password: guest # 密码
    virtual-host: /vhost # 配置虚拟机
    listener:
      direct:
        acknowledge-mode: manual  # 消息开启手动确认

  datasource:
    url: jdbc:mysql://106.75.115.170:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: gwk_632697105qq
    druid:
      initial-size: 10
      min-idle: 40
      max-active: 80
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
